#!/usr/bin/env bash
set -Eeuo pipefail

case "${1:-help}" in
  import)
    zpool import || true
    ;;
  list-pools)
    zpool list || true
    ;;
  list-datasets)
    zfs list || true
    ;;
  *)
    cat <<'EOH'
Usage:
  debz-recovery import
  debz-recovery list-pools
  debz-recovery list-datasets
EOH
    ;;
esac
